(() => {
  const injuryLabel=s=>({ACTIVE:'ACTIVE',QUESTIONABLE:'QUESTIONABLE',DOUBTFUL:'DOUBTFUL',OUT:'OUT',INJURY_RESERVE:'IL',INJURED_RESERVE:'IL',SUSPENDED:'SUSPENDED',DAY_TO_DAY:'DAY-TO-DAY'}[(s||'').toUpperCase()]||(s||'').toUpperCase());
  window.pos=p=>{const x=String(p?.position||'').toUpperCase();if(x==='RELIEF PITCHER'||x==='RP')return 'RP';if(x==='STARTING PITCHER'||x==='SP')return 'SP';if(x==='PITCHER'||x==='P')return 'P';return x||'—'};
  window.elig=p=>{const a=Array.isArray(p?.eligible_positions)?p.eligible_positions:[],primary=pos(p),v=[...new Set(a.map(x=>String(x).toUpperCase()).filter(x=>x!=='RELIEF PITCHER'||primary==='RP'))];return v.length?v.join(' · '):'—'};
  window.statusClass=p=>{const i=(p?.injury_status||'').toUpperCase();if(i&&i!=='ACTIVE')return[injuryLabel(i),'il'];const s=(p?.lineup_slot||'').toUpperCase();if(s==='BENCH')return['BENCH','bench'];if(p?.status==='WAIVERS'||p?.status==='FREEAGENT')return[p.status,'waiver'];return[s||'ACTIVE','active']};
  window.playerRow=(p,waiver=false)=>{const[st,cl]=statusClass(p),i=(p?.injury_status||'').toUpperCase(),it=i&&i!=='ACTIVE'?` · ${esc(injuryLabel(i))}`:'';return `<tr class="row" onclick="openPlayer(${Number(p.id)})"><td><div class="player"><div class="avatar">${esc(initials(p.name))}</div><div><div class="pn">${esc(p.name)}</div><div class="sub">${p.pro_team_id?'MLB team ID '+esc(p.pro_team_id):'Player profile'}${it}</div></div></div></td><td><span class="pos">${esc(pos(p))}</span></td><td><span class="sub">${esc(elig(p))}${p.lineup_slot?' · '+esc(p.lineup_slot):''}</span></td><td><span class="badge ${cl}">${esc(st)}</span></td>${waiver?`<td>${p.percent_owned==null?'—':esc(Number(p.percent_owned).toFixed(1))+'%'}</td>`:''}<td class="pts">${p.total_points==null?'—':esc(Number(p.total_points).toFixed(1))}</td></tr>`};
  const fmt=(v,d=2)=>v==null||v===''?'—':Number(v).toFixed(d);
  const cards=(s,defs)=>defs.filter(x=>s&&s[x.k]!=null).map(x=>`<div class="stat"><span>${x.l}</span><b>${esc(fmt(s[x.k],x.d??2))}</b></div>`).join('');
  window.openPlayer=async function(id){
    $('playerModal').classList.add('on');$('pmName').textContent='Loading player…';$('pmSub').textContent='ESPN fantasy + MLB season';$('pmStats').innerHTML='<div class="loading">Loading season stats…</div>';
    try{
      const j=await api('/espn/player/'+id),p=j.player||{};$('pmName').textContent=p.name||'Player';const injury=(p.injury_status||'').toUpperCase();$('pmSub').textContent=`${pos(p)}${elig(p)!=='—'?' · '+elig(p):''}${injury&&injury!=='ACTIVE'?' · '+injuryLabel(injury):''}`;
      const base=Number(p.total_points);let html='<div class="statgrid">';if(Number.isFinite(base))html+=`<div class="stat"><span>Fantasy season points</span><b>${esc(base.toFixed(1))}</b></div>`;
      let mlb=null;try{const r=await fetch('/mlb/player-stats?name='+encodeURIComponent(p.name));if(r.ok)mlb=await r.json()}catch(e){}
      const stats=mlb?.pitching||mlb?.hitting;const games=Number(stats?.gamesPlayed);if(Number.isFinite(base)&&games>0)html+=`<div class="stat"><span>Average fantasy points / game</span><b>${esc((base/games).toFixed(1))}</b></div>`;if(p.percent_owned!=null)html+=`<div class="stat"><span>Owned</span><b>${esc(Number(p.percent_owned).toFixed(1))}%</b></div>`;if(p.percent_started!=null)html+=`<div class="stat"><span>Started</span><b>${esc(Number(p.percent_started).toFixed(1))}%</b></div>`;html+='</div>';
      if(mlb?.pitching){const x=mlb.pitching;html+='<div class="sectionTitle">2026 MLB Pitching</div><div class="statgrid">'+cards(x,[{l:'Games (G)',k:'gamesPlayed',d:0},{l:'Games Started (GS)',k:'gamesStarted',d:0},{l:'Innings Pitched (IP)',k:'inningsPitched',d:1},{l:'Wins (W)',k:'wins',d:0},{l:'Losses (L)',k:'losses',d:0},{l:'Saves (SV)',k:'saves',d:0},{l:'Strikeouts (K)',k:'strikeOuts',d:0},{l:'ERA',k:'era',d:2},{l:'WHIP',k:'whip',d:2},{l:'Hits Allowed (H)',k:'hits',d:0},{l:'Earned Runs (ER)',k:'earnedRuns',d:0},{l:'Walks (BB)',k:'baseOnBalls',d:0}])+'</div>'}
      else if(mlb?.hitting){const x=mlb.hitting;html+='<div class="sectionTitle">2026 MLB Batting</div><div class="statgrid">'+cards(x,[{l:'Games (G)',k:'gamesPlayed',d:0},{l:'At Bats (AB)',k:'atBats',d:0},{l:'Runs (R)',k:'runs',d:0},{l:'Hits (H)',k:'hits',d:0},{l:'Doubles (2B)',k:'doubles',d:0},{l:'Triples (3B)',k:'triples',d:0},{l:'Home Runs (HR)',k:'homeRuns',d:0},{l:'RBI',k:'rbi',d:0},{l:'Walks (BB)',k:'baseOnBalls',d:0},{l:'Strikeouts (SO)',k:'strikeOuts',d:0},{l:'Stolen Bases (SB)',k:'stolenBases',d:0},{l:'Batting Average (AVG)',k:'avg',d:3},{l:'On-Base % (OBP)',k:'obp',d:3},{l:'Slugging % (SLG)',k:'slg',d:3},{l:'OPS',k:'ops',d:3}])+'</div>'}
      else html+='<div class="notice">MLB season stats are unavailable right now.</div>';
      html+='<div class="notice">Fantasy points are your ESPN league total. Average fantasy points/game = season fantasy points ÷ MLB games played.</div>';$('pmStats').innerHTML=html;
    }catch(e){$('pmStats').innerHTML=`<div class="notice err">${esc(e.message)}</div>`}
  };
})();
